name: Build

on:
  schedule:
    - cron: '10 6 * * *'
  push:
    branches:
      - 'current'
  pull_request:
  workflow_dispatch:

defaults:
  run:
    shell: bash

jobs:
  build-linux:
    strategy:
      matrix:
        compiler: [clang]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
        with:
          ref: 'current'
      - name: Build
        env:
          CC: ${{ matrix.compiler }}
        run: bash bin/build.sh "Ubuntu"
      - uses: actions/upload-artifact@v7
        with:
          path: build/embroidermodder*.tar.gz

  build-macos:
    runs-on: macos-latest
    strategy:
      matrix:
        compiler: [clang]
        cxxcompiler: [clang++]
    steps:
      - uses: actions/checkout@v6
        with:
          ref: 'current'
      - name: Build
        env:
          CC: ${{ matrix.compiler }}
          CXX: ${{ matrix.cxxcompiler }}
        run: bash bin/build.sh "MacOS"
      - uses: actions/upload-artifact@v7
        with:
          path: build/embroidermodder*.app

  build-windows:
    runs-on: windows-latest
    strategy:
      matrix:
        compiler: [clang]
        cxxcompiler: [clang++]
    steps:
      - uses: actions/checkout@v6
        with:
          ref: 'current'
      - name: Build
        env:
          CC: ${{ matrix.compiler }}
          CXX: ${{ matrix.cxxcompiler }}
        run: bash bin/build.sh "Windows"
      - uses: actions/upload-artifact@v7
        with:
          path: build/embroidermodder*.exe
